import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/components/providers/AuthProvider";
import { ModalProvider } from "@/components/providers/ModalProvider";
import SellerProvider from "@/components/providers/SellerProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <SellerProvider>
            <Toaster />
            <ModalProvider />
            <div className="hidden lg:block">
              {children}
            </div>
            <div className="lg:hidden flex text-center items-center h-full ">
              <p>The webpage will only be displayed on large devices</p>
            </div>
          </SellerProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
